<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.AuthorityVerifyRequest</code>
 */
class AuthorityVerifyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 菜单编码
     *
     * Generated from protobuf field <code>string Code = 1;</code>
     */
    protected $Code = '';
    /**
     * 权限值,即MenusReply.MenusNode.ActionsEntry返回的值
     *
     * Generated from protobuf field <code>uint32 ActionValue = 2;</code>
     */
    protected $ActionValue = 0;
    /**
     * 用户id
     *
     * Generated from protobuf field <code>uint32 UserId = 3;</code>
     */
    protected $UserId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Code
     *           菜单编码
     *     @type int $ActionValue
     *           权限值,即MenusReply.MenusNode.ActionsEntry返回的值
     *     @type int $UserId
     *           用户id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 菜单编码
     *
     * Generated from protobuf field <code>string Code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->Code;
    }

    /**
     * 菜单编码
     *
     * Generated from protobuf field <code>string Code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->Code = $var;

        return $this;
    }

    /**
     * 权限值,即MenusReply.MenusNode.ActionsEntry返回的值
     *
     * Generated from protobuf field <code>uint32 ActionValue = 2;</code>
     * @return int
     */
    public function getActionValue()
    {
        return $this->ActionValue;
    }

    /**
     * 权限值,即MenusReply.MenusNode.ActionsEntry返回的值
     *
     * Generated from protobuf field <code>uint32 ActionValue = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setActionValue($var)
    {
        GPBUtil::checkUint32($var);
        $this->ActionValue = $var;

        return $this;
    }

    /**
     * 用户id
     *
     * Generated from protobuf field <code>uint32 UserId = 3;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * 用户id
     *
     * Generated from protobuf field <code>uint32 UserId = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint32($var);
        $this->UserId = $var;

        return $this;
    }

}

