<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 新建用户响应
 *
 * Generated from protobuf message <code>proto.CreateUserReply</code>
 */
class CreateUserReply extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户Id
     *
     * Generated from protobuf field <code>uint32 UserId = 1;</code>
     */
    protected $UserId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $UserId
     *           用户Id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户Id
     *
     * Generated from protobuf field <code>uint32 UserId = 1;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * 用户Id
     *
     * Generated from protobuf field <code>uint32 UserId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint32($var);
        $this->UserId = $var;

        return $this;
    }

}

