<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 新建用户入参
 *
 * Generated from protobuf message <code>proto.CreateUserRequest</code>
 */
class CreateUserRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 账号
     *
     * Generated from protobuf field <code>string Account = 1;</code>
     */
    protected $Account = '';
    /**
     * 密码
     *
     * Generated from protobuf field <code>string Password = 2;</code>
     */
    protected $Password = '';
    /**
     * 昵称
     *
     * Generated from protobuf field <code>string NickName = 3;</code>
     */
    protected $NickName = '';
    /**
     * 手机号码
     *
     * Generated from protobuf field <code>string Mobile = 4;</code>
     */
    protected $Mobile = '';
    /**
     * 邮箱地址
     *
     * Generated from protobuf field <code>string Email = 5;</code>
     */
    protected $Email = '';
    /**
     * 用户详情
     *
     * Generated from protobuf field <code>.proto.UserInfo UserInfo = 6;</code>
     */
    protected $UserInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Account
     *           账号
     *     @type string $Password
     *           密码
     *     @type string $NickName
     *           昵称
     *     @type string $Mobile
     *           手机号码
     *     @type string $Email
     *           邮箱地址
     *     @type \Proto\UserInfo $UserInfo
     *           用户详情
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 账号
     *
     * Generated from protobuf field <code>string Account = 1;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->Account;
    }

    /**
     * 账号
     *
     * Generated from protobuf field <code>string Account = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->Account = $var;

        return $this;
    }

    /**
     * 密码
     *
     * Generated from protobuf field <code>string Password = 2;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->Password;
    }

    /**
     * 密码
     *
     * Generated from protobuf field <code>string Password = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->Password = $var;

        return $this;
    }

    /**
     * 昵称
     *
     * Generated from protobuf field <code>string NickName = 3;</code>
     * @return string
     */
    public function getNickName()
    {
        return $this->NickName;
    }

    /**
     * 昵称
     *
     * Generated from protobuf field <code>string NickName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->NickName = $var;

        return $this;
    }

    /**
     * 手机号码
     *
     * Generated from protobuf field <code>string Mobile = 4;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->Mobile;
    }

    /**
     * 手机号码
     *
     * Generated from protobuf field <code>string Mobile = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->Mobile = $var;

        return $this;
    }

    /**
     * 邮箱地址
     *
     * Generated from protobuf field <code>string Email = 5;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->Email;
    }

    /**
     * 邮箱地址
     *
     * Generated from protobuf field <code>string Email = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->Email = $var;

        return $this;
    }

    /**
     * 用户详情
     *
     * Generated from protobuf field <code>.proto.UserInfo UserInfo = 6;</code>
     * @return \Proto\UserInfo
     */
    public function getUserInfo()
    {
        return isset($this->UserInfo) ? $this->UserInfo : null;
    }

    public function hasUserInfo()
    {
        return isset($this->UserInfo);
    }

    public function clearUserInfo()
    {
        unset($this->UserInfo);
    }

    /**
     * 用户详情
     *
     * Generated from protobuf field <code>.proto.UserInfo UserInfo = 6;</code>
     * @param \Proto\UserInfo $var
     * @return $this
     */
    public function setUserInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\UserInfo::class);
        $this->UserInfo = $var;

        return $this;
    }

}

