<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\GetRoleListReply\RoleListData instead.
     * @deprecated
     */
    class GetRoleListReply_RoleListData {}
}
class_exists(GetRoleListReply\RoleListData::class);
@trigger_error('Proto\GetRoleListReply_RoleListData is deprecated and will be removed in the next major release. Use Proto\GetRoleListReply\RoleListData instead', E_USER_DEPRECATED);

