<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\GetRoleListReply\RoleAuthoritys instead.
     * @deprecated
     */
    class GetRoleListReply_RoleAuthoritys {}
}
class_exists(GetRoleListReply\RoleAuthoritys::class);
@trigger_error('Proto\GetRoleListReply_RoleAuthoritys is deprecated and will be removed in the next major release. Use Proto\GetRoleListReply\RoleAuthoritys instead', E_USER_DEPRECATED);

