<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.GetUserListReply</code>
 */
class GetUserListReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.proto.PaginateReply Paginate = 1;</code>
     */
    protected $Paginate = null;
    /**
     * Generated from protobuf field <code>repeated .proto.GetUserListReply.UserListData Docs = 2;</code>
     */
    private $Docs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\PaginateReply $Paginate
     *     @type \Proto\GetUserListReply\UserListData[]|\Google\Protobuf\Internal\RepeatedField $Docs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.proto.PaginateReply Paginate = 1;</code>
     * @return \Proto\PaginateReply
     */
    public function getPaginate()
    {
        return isset($this->Paginate) ? $this->Paginate : null;
    }

    public function hasPaginate()
    {
        return isset($this->Paginate);
    }

    public function clearPaginate()
    {
        unset($this->Paginate);
    }

    /**
     * Generated from protobuf field <code>.proto.PaginateReply Paginate = 1;</code>
     * @param \Proto\PaginateReply $var
     * @return $this
     */
    public function setPaginate($var)
    {
        GPBUtil::checkMessage($var, \Proto\PaginateReply::class);
        $this->Paginate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.GetUserListReply.UserListData Docs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDocs()
    {
        return $this->Docs;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.GetUserListReply.UserListData Docs = 2;</code>
     * @param \Proto\GetUserListReply\UserListData[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDocs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\GetUserListReply\UserListData::class);
        $this->Docs = $arr;

        return $this;
    }

}

