<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\GetUserListReply\UserListData instead.
     * @deprecated
     */
    class GetUserListReply_UserListData {}
}
class_exists(GetUserListReply\UserListData::class);
@trigger_error('Proto\GetUserListReply_UserListData is deprecated and will be removed in the next major release. Use Proto\GetUserListReply\UserListData instead', E_USER_DEPRECATED);

