<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\MenusReply\MenusNode instead.
     * @deprecated
     */
    class MenusReply_MenusNode {}
}
class_exists(MenusReply\MenusNode::class);
@trigger_error('Proto\MenusReply_MenusNode is deprecated and will be removed in the next major release. Use Proto\MenusReply\MenusNode instead', E_USER_DEPRECATED);

