<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\MenusRequest\MenusNode instead.
     * @deprecated
     */
    class MenusRequest_MenusNode {}
}
class_exists(MenusRequest\MenusNode::class);
@trigger_error('Proto\MenusRequest_MenusNode is deprecated and will be removed in the next major release. Use Proto\MenusRequest\MenusNode instead', E_USER_DEPRECATED);

