<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 分页列表响应
 *
 * Generated from protobuf message <code>proto.PaginateReply</code>
 */
class PaginateReply extends \Google\Protobuf\Internal\Message
{
    /**
     * 页数
     *
     * Generated from protobuf field <code>uint32 Page = 1;</code>
     */
    protected $Page = 0;
    /**
     * 总页数
     *
     * Generated from protobuf field <code>uint32 Pages = 2;</code>
     */
    protected $Pages = 0;
    /**
     * 数据总数
     *
     * Generated from protobuf field <code>uint32 Total = 3;</code>
     */
    protected $Total = 0;
    /**
     * 每页数量
     *
     * Generated from protobuf field <code>uint32 Limit = 4;</code>
     */
    protected $Limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Page
     *           页数
     *     @type int $Pages
     *           总页数
     *     @type int $Total
     *           数据总数
     *     @type int $Limit
     *           每页数量
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 页数
     *
     * Generated from protobuf field <code>uint32 Page = 1;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->Page;
    }

    /**
     * 页数
     *
     * Generated from protobuf field <code>uint32 Page = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkUint32($var);
        $this->Page = $var;

        return $this;
    }

    /**
     * 总页数
     *
     * Generated from protobuf field <code>uint32 Pages = 2;</code>
     * @return int
     */
    public function getPages()
    {
        return $this->Pages;
    }

    /**
     * 总页数
     *
     * Generated from protobuf field <code>uint32 Pages = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPages($var)
    {
        GPBUtil::checkUint32($var);
        $this->Pages = $var;

        return $this;
    }

    /**
     * 数据总数
     *
     * Generated from protobuf field <code>uint32 Total = 3;</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->Total;
    }

    /**
     * 数据总数
     *
     * Generated from protobuf field <code>uint32 Total = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint32($var);
        $this->Total = $var;

        return $this;
    }

    /**
     * 每页数量
     *
     * Generated from protobuf field <code>uint32 Limit = 4;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->Limit;
    }

    /**
     * 每页数量
     *
     * Generated from protobuf field <code>uint32 Limit = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->Limit = $var;

        return $this;
    }

}

