<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 分页列表入参
 *
 * Generated from protobuf message <code>proto.PaginateRequest</code>
 */
class PaginateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 页数
     *
     * Generated from protobuf field <code>uint32 Page = 1;</code>
     */
    protected $Page = 0;
    /**
     * 每页数量
     *
     * Generated from protobuf field <code>uint32 Limit = 2;</code>
     */
    protected $Limit = 0;
    /**
     * 搜索关键字,key为要搜索的值,value为数据库字段，多个value匹配其中一个,如模糊搜索名称或描述
     *
     * Generated from protobuf field <code>map<string, .google.protobuf.ListValue> Search = 3;</code>
     */
    private $Search;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Page
     *           页数
     *     @type int $Limit
     *           每页数量
     *     @type array|\Google\Protobuf\Internal\MapField $Search
     *           搜索关键字,key为要搜索的值,value为数据库字段，多个value匹配其中一个,如模糊搜索名称或描述
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 页数
     *
     * Generated from protobuf field <code>uint32 Page = 1;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->Page;
    }

    /**
     * 页数
     *
     * Generated from protobuf field <code>uint32 Page = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkUint32($var);
        $this->Page = $var;

        return $this;
    }

    /**
     * 每页数量
     *
     * Generated from protobuf field <code>uint32 Limit = 2;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->Limit;
    }

    /**
     * 每页数量
     *
     * Generated from protobuf field <code>uint32 Limit = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkUint32($var);
        $this->Limit = $var;

        return $this;
    }

    /**
     * 搜索关键字,key为要搜索的值,value为数据库字段，多个value匹配其中一个,如模糊搜索名称或描述
     *
     * Generated from protobuf field <code>map<string, .google.protobuf.ListValue> Search = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSearch()
    {
        return $this->Search;
    }

    /**
     * 搜索关键字,key为要搜索的值,value为数据库字段，多个value匹配其中一个,如模糊搜索名称或描述
     *
     * Generated from protobuf field <code>map<string, .google.protobuf.ListValue> Search = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSearch($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\ListValue::class);
        $this->Search = $arr;

        return $this;
    }

}

