<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

if (false) {
    /**
     * This class is deprecated. Use Proto\PermissionsTplRequest\PermissionsNode instead.
     * @deprecated
     */
    class PermissionsTplRequest_PermissionsNode {}
}
class_exists(PermissionsTplRequest\PermissionsNode::class);
@trigger_error('Proto\PermissionsTplRequest_PermissionsNode is deprecated and will be removed in the next major release. Use Proto\PermissionsTplRequest\PermissionsNode instead', E_USER_DEPRECATED);

