<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 角色详情
 *
 * Generated from protobuf message <code>proto.RoleInfo</code>
 */
class RoleInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * 角色名
     *
     * Generated from protobuf field <code>string Name = 1;</code>
     */
    protected $Name = '';
    /**
     * 备注,新增可不传，编辑必传
     *
     * Generated from protobuf field <code>string Remark = 2;</code>
     */
    protected $Remark = '';
    /**
     * 状态,新增可不传，编辑必传
     *
     * Generated from protobuf field <code>bool Status = 3;</code>
     */
    protected $Status = false;
    /**
     * 排序,新增可不传，编辑必传
     *
     * Generated from protobuf field <code>uint32 Sequence = 4;</code>
     */
    protected $Sequence = 0;
    /**
     * 权限
     *
     * Generated from protobuf field <code>map<string, uint32> Permissions = 5;</code>
     */
    private $Permissions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Name
     *           角色名
     *     @type string $Remark
     *           备注,新增可不传，编辑必传
     *     @type bool $Status
     *           状态,新增可不传，编辑必传
     *     @type int $Sequence
     *           排序,新增可不传，编辑必传
     *     @type array|\Google\Protobuf\Internal\MapField $Permissions
     *           权限
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 角色名
     *
     * Generated from protobuf field <code>string Name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * 角色名
     *
     * Generated from protobuf field <code>string Name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * 备注,新增可不传，编辑必传
     *
     * Generated from protobuf field <code>string Remark = 2;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->Remark;
    }

    /**
     * 备注,新增可不传，编辑必传
     *
     * Generated from protobuf field <code>string Remark = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->Remark = $var;

        return $this;
    }

    /**
     * 状态,新增可不传，编辑必传
     *
     * Generated from protobuf field <code>bool Status = 3;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * 状态,新增可不传，编辑必传
     *
     * Generated from protobuf field <code>bool Status = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->Status = $var;

        return $this;
    }

    /**
     * 排序,新增可不传，编辑必传
     *
     * Generated from protobuf field <code>uint32 Sequence = 4;</code>
     * @return int
     */
    public function getSequence()
    {
        return $this->Sequence;
    }

    /**
     * 排序,新增可不传，编辑必传
     *
     * Generated from protobuf field <code>uint32 Sequence = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSequence($var)
    {
        GPBUtil::checkUint32($var);
        $this->Sequence = $var;

        return $this;
    }

    /**
     * 权限
     *
     * Generated from protobuf field <code>map<string, uint32> Permissions = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPermissions()
    {
        return $this->Permissions;
    }

    /**
     * 权限
     *
     * Generated from protobuf field <code>map<string, uint32> Permissions = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPermissions($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->Permissions = $arr;

        return $this;
    }

}

