<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.Token</code>
 */
class Token extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户登录凭证
     *
     * Generated from protobuf field <code>string Token = 1;</code>
     */
    protected $Token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Token
     *           用户登录凭证
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户登录凭证
     *
     * Generated from protobuf field <code>string Token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->Token;
    }

    /**
     * 用户登录凭证
     *
     * Generated from protobuf field <code>string Token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->Token = $var;

        return $this;
    }

}

