<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Token验证响应
 *
 * Generated from protobuf message <code>proto.TokenVerifyReply</code>
 */
class TokenVerifyReply extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户id
     *
     * Generated from protobuf field <code>uint32 UserId = 1;</code>
     */
    protected $UserId = 0;
    /**
     * 过期时间
     *
     * Generated from protobuf field <code>uint64 ExpiresAt = 2;</code>
     */
    protected $ExpiresAt = 0;
    /**
     * 发行标记
     *
     * Generated from protobuf field <code>string Issuer = 3;</code>
     */
    protected $Issuer = '';
    /**
     * 用户当前应用菜单权限
     *
     * Generated from protobuf field <code>repeated .proto.MenusReply.MenusNode MenuPermissions = 4;</code>
     */
    private $MenuPermissions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $UserId
     *           用户id
     *     @type int|string $ExpiresAt
     *           过期时间
     *     @type string $Issuer
     *           发行标记
     *     @type \Proto\MenusReply\MenusNode[]|\Google\Protobuf\Internal\RepeatedField $MenuPermissions
     *           用户当前应用菜单权限
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户id
     *
     * Generated from protobuf field <code>uint32 UserId = 1;</code>
     * @return int
     */
    public function getUserId()
    {
        return $this->UserId;
    }

    /**
     * 用户id
     *
     * Generated from protobuf field <code>uint32 UserId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkUint32($var);
        $this->UserId = $var;

        return $this;
    }

    /**
     * 过期时间
     *
     * Generated from protobuf field <code>uint64 ExpiresAt = 2;</code>
     * @return int|string
     */
    public function getExpiresAt()
    {
        return $this->ExpiresAt;
    }

    /**
     * 过期时间
     *
     * Generated from protobuf field <code>uint64 ExpiresAt = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpiresAt($var)
    {
        GPBUtil::checkUint64($var);
        $this->ExpiresAt = $var;

        return $this;
    }

    /**
     * 发行标记
     *
     * Generated from protobuf field <code>string Issuer = 3;</code>
     * @return string
     */
    public function getIssuer()
    {
        return $this->Issuer;
    }

    /**
     * 发行标记
     *
     * Generated from protobuf field <code>string Issuer = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIssuer($var)
    {
        GPBUtil::checkString($var, True);
        $this->Issuer = $var;

        return $this;
    }

    /**
     * 用户当前应用菜单权限
     *
     * Generated from protobuf field <code>repeated .proto.MenusReply.MenusNode MenuPermissions = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMenuPermissions()
    {
        return $this->MenuPermissions;
    }

    /**
     * 用户当前应用菜单权限
     *
     * Generated from protobuf field <code>repeated .proto.MenusReply.MenusNode MenuPermissions = 4;</code>
     * @param \Proto\MenusReply\MenusNode[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMenuPermissions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\MenusReply\MenusNode::class);
        $this->MenuPermissions = $arr;

        return $this;
    }

}

