<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 更新用户入参
 *
 * Generated from protobuf message <code>proto.UpdateUserInfoRequest</code>
 */
class UpdateUserInfoRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户id
     *
     * Generated from protobuf field <code>uint32 Id = 1;</code>
     */
    protected $Id = 0;
    /**
     * 用户详情
     *
     * Generated from protobuf field <code>.proto.UserInfo UserInfo = 2;</code>
     */
    protected $UserInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Id
     *           用户id
     *     @type \Proto\UserInfo $UserInfo
     *           用户详情
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户id
     *
     * Generated from protobuf field <code>uint32 Id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * 用户id
     *
     * Generated from protobuf field <code>uint32 Id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * 用户详情
     *
     * Generated from protobuf field <code>.proto.UserInfo UserInfo = 2;</code>
     * @return \Proto\UserInfo
     */
    public function getUserInfo()
    {
        return isset($this->UserInfo) ? $this->UserInfo : null;
    }

    public function hasUserInfo()
    {
        return isset($this->UserInfo);
    }

    public function clearUserInfo()
    {
        unset($this->UserInfo);
    }

    /**
     * 用户详情
     *
     * Generated from protobuf field <code>.proto.UserInfo UserInfo = 2;</code>
     * @param \Proto\UserInfo $var
     * @return $this
     */
    public function setUserInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\UserInfo::class);
        $this->UserInfo = $var;

        return $this;
    }

}

