<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.UserPassVerifyRequest</code>
 */
class UserPassVerifyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 类型，account|email|mobile
     *
     * Generated from protobuf field <code>string Type = 1;</code>
     */
    protected $Type = '';
    /**
     * 对应类型的值
     *
     * Generated from protobuf field <code>string Value = 2;</code>
     */
    protected $Value = '';
    /**
     * 密码
     *
     * Generated from protobuf field <code>string Password = 3;</code>
     */
    protected $Password = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Type
     *           类型，account|email|mobile
     *     @type string $Value
     *           对应类型的值
     *     @type string $Password
     *           密码
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 类型，account|email|mobile
     *
     * Generated from protobuf field <code>string Type = 1;</code>
     * @return string
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * 类型，account|email|mobile
     *
     * Generated from protobuf field <code>string Type = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->Type = $var;

        return $this;
    }

    /**
     * 对应类型的值
     *
     * Generated from protobuf field <code>string Value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->Value;
    }

    /**
     * 对应类型的值
     *
     * Generated from protobuf field <code>string Value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->Value = $var;

        return $this;
    }

    /**
     * 密码
     *
     * Generated from protobuf field <code>string Password = 3;</code>
     * @return string
     */
    public function getPassword()
    {
        return $this->Password;
    }

    /**
     * 密码
     *
     * Generated from protobuf field <code>string Password = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->Password = $var;

        return $this;
    }

}

