<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 用户详情
 *
 * Generated from protobuf message <code>proto.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * 姓名
     *
     * Generated from protobuf field <code>string RealName = 1;</code>
     */
    protected $RealName = '';
    /**
     * 年龄
     *
     * Generated from protobuf field <code>uint32 Age = 2;</code>
     */
    protected $Age = 0;
    /**
     * 性别
     *
     * Generated from protobuf field <code>uint32 Sex = 3;</code>
     */
    protected $Sex = 0;
    /**
     * 民族
     *
     * Generated from protobuf field <code>string Nation = 4;</code>
     */
    protected $Nation = '';
    /**
     * 住址
     *
     * Generated from protobuf field <code>string Address = 5;</code>
     */
    protected $Address = '';
    /**
     * 身份证号码   
     *
     * Generated from protobuf field <code>string IdCard = 6;</code>
     */
    protected $IdCard = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RealName
     *           姓名
     *     @type int $Age
     *           年龄
     *     @type int $Sex
     *           性别
     *     @type string $Nation
     *           民族
     *     @type string $Address
     *           住址
     *     @type string $IdCard
     *           身份证号码   
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 姓名
     *
     * Generated from protobuf field <code>string RealName = 1;</code>
     * @return string
     */
    public function getRealName()
    {
        return $this->RealName;
    }

    /**
     * 姓名
     *
     * Generated from protobuf field <code>string RealName = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRealName($var)
    {
        GPBUtil::checkString($var, True);
        $this->RealName = $var;

        return $this;
    }

    /**
     * 年龄
     *
     * Generated from protobuf field <code>uint32 Age = 2;</code>
     * @return int
     */
    public function getAge()
    {
        return $this->Age;
    }

    /**
     * 年龄
     *
     * Generated from protobuf field <code>uint32 Age = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAge($var)
    {
        GPBUtil::checkUint32($var);
        $this->Age = $var;

        return $this;
    }

    /**
     * 性别
     *
     * Generated from protobuf field <code>uint32 Sex = 3;</code>
     * @return int
     */
    public function getSex()
    {
        return $this->Sex;
    }

    /**
     * 性别
     *
     * Generated from protobuf field <code>uint32 Sex = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSex($var)
    {
        GPBUtil::checkUint32($var);
        $this->Sex = $var;

        return $this;
    }

    /**
     * 民族
     *
     * Generated from protobuf field <code>string Nation = 4;</code>
     * @return string
     */
    public function getNation()
    {
        return $this->Nation;
    }

    /**
     * 民族
     *
     * Generated from protobuf field <code>string Nation = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNation($var)
    {
        GPBUtil::checkString($var, True);
        $this->Nation = $var;

        return $this;
    }

    /**
     * 住址
     *
     * Generated from protobuf field <code>string Address = 5;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->Address;
    }

    /**
     * 住址
     *
     * Generated from protobuf field <code>string Address = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->Address = $var;

        return $this;
    }

    /**
     * 身份证号码   
     *
     * Generated from protobuf field <code>string IdCard = 6;</code>
     * @return string
     */
    public function getIdCard()
    {
        return $this->IdCard;
    }

    /**
     * 身份证号码   
     *
     * Generated from protobuf field <code>string IdCard = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setIdCard($var)
    {
        GPBUtil::checkString($var, True);
        $this->IdCard = $var;

        return $this;
    }

}

