<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.VerifyValidateCodeRequest</code>
 */
class VerifyValidateCodeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * 验证码ID
     *
     * Generated from protobuf field <code>string CodeId = 1;</code>
     */
    protected $CodeId = '';
    /**
     * 验证码内容
     *
     * Generated from protobuf field <code>string CodeValue = 2;</code>
     */
    protected $CodeValue = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $CodeId
     *           验证码ID
     *     @type string $CodeValue
     *           验证码内容
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 验证码ID
     *
     * Generated from protobuf field <code>string CodeId = 1;</code>
     * @return string
     */
    public function getCodeId()
    {
        return $this->CodeId;
    }

    /**
     * 验证码ID
     *
     * Generated from protobuf field <code>string CodeId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCodeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CodeId = $var;

        return $this;
    }

    /**
     * 验证码内容
     *
     * Generated from protobuf field <code>string CodeValue = 2;</code>
     * @return string
     */
    public function getCodeValue()
    {
        return $this->CodeValue;
    }

    /**
     * 验证码内容
     *
     * Generated from protobuf field <code>string CodeValue = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCodeValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->CodeValue = $var;

        return $this;
    }

}

