<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto\GetUserListReply;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.GetUserListReply.UserListData</code>
 */
class UserListData extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户Id
     *
     * Generated from protobuf field <code>uint32 Id = 1;</code>
     */
    protected $Id = 0;
    /**
     * 创建时间
     *
     * Generated from protobuf field <code>string CreatedAt = 2;</code>
     */
    protected $CreatedAt = '';
    /**
     * 最近更新时间
     *
     * Generated from protobuf field <code>string UpdatedAt = 3;</code>
     */
    protected $UpdatedAt = '';
    /**
     * 账号
     *
     * Generated from protobuf field <code>string Account = 4;</code>
     */
    protected $Account = '';
    /**
     * 昵称
     *
     * Generated from protobuf field <code>string NickName = 5;</code>
     */
    protected $NickName = '';
    /**
     * 手机号
     *
     * Generated from protobuf field <code>string Mobile = 6;</code>
     */
    protected $Mobile = '';
    /**
     * 邮箱
     *
     * Generated from protobuf field <code>string Email = 7;</code>
     */
    protected $Email = '';
    /**
     * 状态
     *
     * Generated from protobuf field <code>bool Status = 8;</code>
     */
    protected $Status = false;
    /**
     * 最后登录时间
     *
     * Generated from protobuf field <code>string LoginedAt = 9;</code>
     */
    protected $LoginedAt = '';
    /**
     * 用户详情
     *
     * Generated from protobuf field <code>.proto.UserInfo Info = 10;</code>
     */
    protected $Info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Id
     *           用户Id
     *     @type string $CreatedAt
     *           创建时间
     *     @type string $UpdatedAt
     *           最近更新时间
     *     @type string $Account
     *           账号
     *     @type string $NickName
     *           昵称
     *     @type string $Mobile
     *           手机号
     *     @type string $Email
     *           邮箱
     *     @type bool $Status
     *           状态
     *     @type string $LoginedAt
     *           最后登录时间
     *     @type \Proto\UserInfo $Info
     *           用户详情
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户Id
     *
     * Generated from protobuf field <code>uint32 Id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * 用户Id
     *
     * Generated from protobuf field <code>uint32 Id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * 创建时间
     *
     * Generated from protobuf field <code>string CreatedAt = 2;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->CreatedAt;
    }

    /**
     * 创建时间
     *
     * Generated from protobuf field <code>string CreatedAt = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->CreatedAt = $var;

        return $this;
    }

    /**
     * 最近更新时间
     *
     * Generated from protobuf field <code>string UpdatedAt = 3;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->UpdatedAt;
    }

    /**
     * 最近更新时间
     *
     * Generated from protobuf field <code>string UpdatedAt = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->UpdatedAt = $var;

        return $this;
    }

    /**
     * 账号
     *
     * Generated from protobuf field <code>string Account = 4;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->Account;
    }

    /**
     * 账号
     *
     * Generated from protobuf field <code>string Account = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->Account = $var;

        return $this;
    }

    /**
     * 昵称
     *
     * Generated from protobuf field <code>string NickName = 5;</code>
     * @return string
     */
    public function getNickName()
    {
        return $this->NickName;
    }

    /**
     * 昵称
     *
     * Generated from protobuf field <code>string NickName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->NickName = $var;

        return $this;
    }

    /**
     * 手机号
     *
     * Generated from protobuf field <code>string Mobile = 6;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->Mobile;
    }

    /**
     * 手机号
     *
     * Generated from protobuf field <code>string Mobile = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->Mobile = $var;

        return $this;
    }

    /**
     * 邮箱
     *
     * Generated from protobuf field <code>string Email = 7;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->Email;
    }

    /**
     * 邮箱
     *
     * Generated from protobuf field <code>string Email = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->Email = $var;

        return $this;
    }

    /**
     * 状态
     *
     * Generated from protobuf field <code>bool Status = 8;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * 状态
     *
     * Generated from protobuf field <code>bool Status = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->Status = $var;

        return $this;
    }

    /**
     * 最后登录时间
     *
     * Generated from protobuf field <code>string LoginedAt = 9;</code>
     * @return string
     */
    public function getLoginedAt()
    {
        return $this->LoginedAt;
    }

    /**
     * 最后登录时间
     *
     * Generated from protobuf field <code>string LoginedAt = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setLoginedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->LoginedAt = $var;

        return $this;
    }

    /**
     * 用户详情
     *
     * Generated from protobuf field <code>.proto.UserInfo Info = 10;</code>
     * @return \Proto\UserInfo
     */
    public function getInfo()
    {
        return isset($this->Info) ? $this->Info : null;
    }

    public function hasInfo()
    {
        return isset($this->Info);
    }

    public function clearInfo()
    {
        unset($this->Info);
    }

    /**
     * 用户详情
     *
     * Generated from protobuf field <code>.proto.UserInfo Info = 10;</code>
     * @param \Proto\UserInfo $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \Proto\UserInfo::class);
        $this->Info = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(UserListData::class, \Proto\GetUserListReply_UserListData::class);

