<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto\MenusReply;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.MenusReply.MenusNode</code>
 */
class MenusNode extends \Google\Protobuf\Internal\Message
{
    /**
     * 菜单编码
     *
     * Generated from protobuf field <code>string Code = 1;</code>
     */
    protected $Code = '';
    /**
     * 菜单名称
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    protected $Name = '';
    /**
     * 排序
     *
     * Generated from protobuf field <code>uint32 Sequence = 3;</code>
     */
    protected $Sequence = 0;
    /**
     * 路由
     *
     * Generated from protobuf field <code>string Uri = 4;</code>
     */
    protected $Uri = '';
    /**
     * 授权动作
     *
     * Generated from protobuf field <code>map<string, uint32> Actions = 5;</code>
     */
    private $Actions;
    /**
     * 下级节点
     *
     * Generated from protobuf field <code>repeated .proto.MenusReply.MenusNode Children = 7;</code>
     */
    private $Children;
    /**
     * 备注
     *
     * Generated from protobuf field <code>string Remark = 6;</code>
     */
    protected $Remark = '';
    /**
     * 状态
     *
     * Generated from protobuf field <code>bool Status = 8;</code>
     */
    protected $Status = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Code
     *           菜单编码
     *     @type string $Name
     *           菜单名称
     *     @type int $Sequence
     *           排序
     *     @type string $Uri
     *           路由
     *     @type array|\Google\Protobuf\Internal\MapField $Actions
     *           授权动作
     *     @type \Proto\MenusReply\MenusNode[]|\Google\Protobuf\Internal\RepeatedField $Children
     *           下级节点
     *     @type string $Remark
     *           备注
     *     @type bool $Status
     *           状态
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 菜单编码
     *
     * Generated from protobuf field <code>string Code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->Code;
    }

    /**
     * 菜单编码
     *
     * Generated from protobuf field <code>string Code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->Code = $var;

        return $this;
    }

    /**
     * 菜单名称
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * 菜单名称
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>uint32 Sequence = 3;</code>
     * @return int
     */
    public function getSequence()
    {
        return $this->Sequence;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>uint32 Sequence = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSequence($var)
    {
        GPBUtil::checkUint32($var);
        $this->Sequence = $var;

        return $this;
    }

    /**
     * 路由
     *
     * Generated from protobuf field <code>string Uri = 4;</code>
     * @return string
     */
    public function getUri()
    {
        return $this->Uri;
    }

    /**
     * 路由
     *
     * Generated from protobuf field <code>string Uri = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->Uri = $var;

        return $this;
    }

    /**
     * 授权动作
     *
     * Generated from protobuf field <code>map<string, uint32> Actions = 5;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getActions()
    {
        return $this->Actions;
    }

    /**
     * 授权动作
     *
     * Generated from protobuf field <code>map<string, uint32> Actions = 5;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setActions($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->Actions = $arr;

        return $this;
    }

    /**
     * 下级节点
     *
     * Generated from protobuf field <code>repeated .proto.MenusReply.MenusNode Children = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getChildren()
    {
        return $this->Children;
    }

    /**
     * 下级节点
     *
     * Generated from protobuf field <code>repeated .proto.MenusReply.MenusNode Children = 7;</code>
     * @param \Proto\MenusReply\MenusNode[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setChildren($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\MenusReply\MenusNode::class);
        $this->Children = $arr;

        return $this;
    }

    /**
     * 备注
     *
     * Generated from protobuf field <code>string Remark = 6;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->Remark;
    }

    /**
     * 备注
     *
     * Generated from protobuf field <code>string Remark = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->Remark = $var;

        return $this;
    }

    /**
     * 状态
     *
     * Generated from protobuf field <code>bool Status = 8;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * 状态
     *
     * Generated from protobuf field <code>bool Status = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->Status = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MenusNode::class, \Proto\MenusReply_MenusNode::class);

