<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto

namespace Proto\GetRoleListReply;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.GetRoleListReply.RoleListData</code>
 */
class RoleListData extends \Google\Protobuf\Internal\Message
{
    /**
     * 角色Id
     *
     * Generated from protobuf field <code>uint32 Id = 1;</code>
     */
    protected $Id = 0;
    /**
     * 创建时间
     *
     * Generated from protobuf field <code>string CreatedAt = 2;</code>
     */
    protected $CreatedAt = '';
    /**
     * 最近更新时间
     *
     * Generated from protobuf field <code>string UpdatedAt = 3;</code>
     */
    protected $UpdatedAt = '';
    /**
     * 角色名
     *
     * Generated from protobuf field <code>string Name = 4;</code>
     */
    protected $Name = '';
    /**
     * 备注
     *
     * Generated from protobuf field <code>string Remark = 5;</code>
     */
    protected $Remark = '';
    /**
     * 排序
     *
     * Generated from protobuf field <code>uint32 Sequence = 6;</code>
     */
    protected $Sequence = 0;
    /**
     * 状态
     *
     * Generated from protobuf field <code>bool Status = 7;</code>
     */
    protected $Status = false;
    /**
     * 角色权限详情
     *
     * Generated from protobuf field <code>repeated .proto.GetRoleListReply.RoleAuthoritys RoleAuthoritys = 8;</code>
     */
    private $RoleAuthoritys;
    /**
     * 关联用户id
     *
     * Generated from protobuf field <code>repeated uint32 AssUserIds = 9;</code>
     */
    private $AssUserIds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Id
     *           角色Id
     *     @type string $CreatedAt
     *           创建时间
     *     @type string $UpdatedAt
     *           最近更新时间
     *     @type string $Name
     *           角色名
     *     @type string $Remark
     *           备注
     *     @type int $Sequence
     *           排序
     *     @type bool $Status
     *           状态
     *     @type \Proto\GetRoleListReply\RoleAuthoritys[]|\Google\Protobuf\Internal\RepeatedField $RoleAuthoritys
     *           角色权限详情
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $AssUserIds
     *           关联用户id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct($data);
    }

    /**
     * 角色Id
     *
     * Generated from protobuf field <code>uint32 Id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * 角色Id
     *
     * Generated from protobuf field <code>uint32 Id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint32($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * 创建时间
     *
     * Generated from protobuf field <code>string CreatedAt = 2;</code>
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->CreatedAt;
    }

    /**
     * 创建时间
     *
     * Generated from protobuf field <code>string CreatedAt = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->CreatedAt = $var;

        return $this;
    }

    /**
     * 最近更新时间
     *
     * Generated from protobuf field <code>string UpdatedAt = 3;</code>
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->UpdatedAt;
    }

    /**
     * 最近更新时间
     *
     * Generated from protobuf field <code>string UpdatedAt = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->UpdatedAt = $var;

        return $this;
    }

    /**
     * 角色名
     *
     * Generated from protobuf field <code>string Name = 4;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * 角色名
     *
     * Generated from protobuf field <code>string Name = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * 备注
     *
     * Generated from protobuf field <code>string Remark = 5;</code>
     * @return string
     */
    public function getRemark()
    {
        return $this->Remark;
    }

    /**
     * 备注
     *
     * Generated from protobuf field <code>string Remark = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRemark($var)
    {
        GPBUtil::checkString($var, True);
        $this->Remark = $var;

        return $this;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>uint32 Sequence = 6;</code>
     * @return int
     */
    public function getSequence()
    {
        return $this->Sequence;
    }

    /**
     * 排序
     *
     * Generated from protobuf field <code>uint32 Sequence = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setSequence($var)
    {
        GPBUtil::checkUint32($var);
        $this->Sequence = $var;

        return $this;
    }

    /**
     * 状态
     *
     * Generated from protobuf field <code>bool Status = 7;</code>
     * @return bool
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * 状态
     *
     * Generated from protobuf field <code>bool Status = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkBool($var);
        $this->Status = $var;

        return $this;
    }

    /**
     * 角色权限详情
     *
     * Generated from protobuf field <code>repeated .proto.GetRoleListReply.RoleAuthoritys RoleAuthoritys = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoleAuthoritys()
    {
        return $this->RoleAuthoritys;
    }

    /**
     * 角色权限详情
     *
     * Generated from protobuf field <code>repeated .proto.GetRoleListReply.RoleAuthoritys RoleAuthoritys = 8;</code>
     * @param \Proto\GetRoleListReply\RoleAuthoritys[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoleAuthoritys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\GetRoleListReply\RoleAuthoritys::class);
        $this->RoleAuthoritys = $arr;

        return $this;
    }

    /**
     * 关联用户id
     *
     * Generated from protobuf field <code>repeated uint32 AssUserIds = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAssUserIds()
    {
        return $this->AssUserIds;
    }

    /**
     * 关联用户id
     *
     * Generated from protobuf field <code>repeated uint32 AssUserIds = 9;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAssUserIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->AssUserIds = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(RoleListData::class, \Proto\GetRoleListReply_RoleListData::class);

